### ISSUE TITLE
Captcha box always shows "Captcha mismatch" in red color

### ISSUE THREAD

**Issue by srautonu** [srautonu/AWorDS#4]
When the box is just shown, it already shows "captcha mismatch" which seems wrong.

Also, after you put the captcha correctly and is able to upload the files successfully, it still shows "captcha mismatch".

**Comment by alatabbi** [comment]
I couldn't reproduce this error, when open the page for the first time it
looks like the attached photo, maybe you see the missmatch error message if
you refresh the page (by hitting F5 or the refresh button, but this is
fine),
Please check again and see if you still have this error,
However I chnaged the color of the captcha text form red to blue, to avoid
confusion.

On 25 January 2016 at 18:01, srautonu notifications@github.com wrote:

> Assigned #4 https://github.com/srautonu/MAW/issues/4 to @alatabbi
> https://github.com/alatabbi.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/srautonu/MAW/issues/4#event-525337267.

## 

~A
