### ISSUE TITLE
How long is an experiment active?

### ISSUE THREAD

**Issue by srautonu** [srautonu/AWorDS#5]
How long is an experiment retained? 
Is there any way to go back to an earlier experiment data? (When I try to create a new experiment, often I get name conflict - already exists error)

**Comment by alatabbi** [comment]
The user session is set to expire after 20 min after the last activity,
this is standard, I will add a trigger to remove the experiment folder and
its content when the session expires, so the next user can reuse the
experiment name again.

To enable the user to go back a previously created experiment, this is a
bit problematic, we have to implement full membership logic, meaning the
user has to signup/signin  to be able to use the site. also we have to
maintain all the user's data, lets do this in the next stage when we have
lots of users and they demand this feature.

On 25 January 2016 at 18:04, srautonu notifications@github.com wrote:

> Assigned #5 https://github.com/srautonu/MAW/issues/5 to @alatabbi
> https://github.com/alatabbi.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/srautonu/MAW/issues/5#event-525340872.

## 

~A

**Comment by srautonu** [comment]
Makes sense. Thanks for the explanation
